src/Entity/Usuario.php
<?php

namespace App\Entity;

use App\Repository\UsuarioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsuarioRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class Usuario implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $nombre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $foto_perfil = null;

    #[ORM\OneToMany(targetEntity: Favorito::class, mappedBy: 'usuario', cascade: ['persist', 'remove'], fetch: 'LAZY')]
    private Collection $favoritos;

    #[ORM\OneToMany(targetEntity: VerMasTarde::class, mappedBy: 'usuario', cascade: ['persist', 'remove'], fetch: 'LAZY')]
    private Collection $verMasTardes;

    public function __construct()
    {
        $this->favoritos = new ArrayCollection();
        $this->verMasTardes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getFotoPerfil(): ?string
    {
        return $this->foto_perfil;
    }

    public function setFotoPerfil(?string $foto_perfil): static
    {
        $this->foto_perfil = $foto_perfil;

        return $this;
    }

    /**
     * @return Collection<int, Favorito>
     */
    public function getFavoritos(): Collection
    {
        return $this->favoritos;
    }

    public function addFavorito(Favorito $favorito): static
    {
        if (!$this->favoritos->contains($favorito)) {
            $this->favoritos->add($favorito);
            $favorito->setUsuario($this);
        }

        return $this;
    }

    public function removeFavorito(Favorito $favorito): static
    {
        if ($this->favoritos->removeElement($favorito)) {
            // set the owning side to null (unless already changed)
            if ($favorito->getUsuario() === $this) {
                $favorito->setUsuario(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, VerMasTarde>
     */
    public function getVerMasTardes(): Collection
    {
        return $this->verMasTardes;
    }

    public function addVerMasTarde(VerMasTarde $verMasTarde): static
    {
        if (!$this->verMasTardes->contains($verMasTarde)) {
            $this->verMasTardes->add($verMasTarde);
            $verMasTarde->setUsuario($this);
        }

        return $this;
    }

    public function removeVerMasTarde(VerMasTarde $verMasTarde): static
    {
        if ($this->verMasTardes->removeElement($verMasTarde)) {
            // set the owning side to null (unless already changed)
            if ($verMasTarde->getUsuario() === $this) {
                $verMasTarde->setUsuario(null);
            }
        }

        return $this;
    }
    

    
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
        {% endblock %}
    </head>
    <body>
        <header>
            
      <div class="group">
        <svg viewBox="0 0 24 24" aria-hidden="true" class="search-icon">
            <g><path d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"></path></g>
        </svg>

        <input id="query" class="input" type="search" placeholder="Buscar..." name="searchbar" />
        </div>
            
            <div class="header-center">
                <nav>
                    <ul class="contenedorLi">
                        <li><a href="{{ path('home') }}" class="{{ app.request.get('_route') == 'app_home' ? 'active' : '' }}">Inicio</a></li>
                        <li><a href="{{ path('app_peliculas') }}" class="{{ app.request.get('_route') == 'ruta_peliculas' ? 'active' : '' }}">Películas</a></li>
                        <li><a href="{{ path('app_series') }}" class="{{ app.request.get('_route') == 'ruta_series' ? 'active' : '' }}">Series</a></li>
                        <li><a href="{{ path('vermas_lista') }}" class="{{ app.request.get('_route') == 'vermas_lista' ? 'active' : '' }}">Ver más tarde</a></li>
                    </ul>
                </nav>
            </div>
            <div class="header-right">
                <div class="profile-info">
                    {% if app.user %}
                        <div class="profile-container">
                            <span>{{ app.user.nombre|capitalize }}</span>
                            <img class="profile-icon" src="{% if app.user.fotoPerfil %}{{ asset('uploads/' ~ app.user.fotoPerfil) }}{% else %}https://i2.pngimg.me/thumb/f/720/c3f2c592f9.jpg{% endif %}" alt="Foto de perfil" onclick="toggleMenu()">
                            <div id="dropdown-menu" class="dropdown-menu">
                                <ul>
                                    <li><a href="{{ path('favoritos_lista') }}">Mis favoritos</a></li>
                                    <li><a href="#">Ajustes</a></li>
                                    <li><a href="#">Perfil</a></li>
                                    <li><a href="{{ path('app_logout') }}">Cerrar sesión</a></li>
                                </ul>
                            </div>
                        </div>
                    {% else %}
                        <p>No has iniciado sesión.</p>
                    {% endif %}
                </div>
            </div>
        </header>

        {% block body %}{% endblock %}

        <script>
            function toggleMenu() {
                const menu = document.getElementById('dropdown-menu');
                menu.style.display = menu.style.display === 'block' ? 'none' : 'block';
            }

            // Oculta el menú al hacer clic fuera de él
            document.addEventListener('click', function (event) {
                const menu = document.getElementById('dropdown-menu');
                const profileIcon = document.querySelector('.profile-icon');
                if (menu && !menu.contains(event.target) && event.target !== profileIcon) {
                    menu.style.display = 'none';
                }
            });

            document.addEventListener("scroll", () => {
            const header = document.querySelector("header");
            if (window.scrollY > 50) { // Si el usuario hace scroll más de 50px
                header.classList.add("scrolled");
            } else {
                header.classList.remove("scrolled");
            }
        });

        </script>

        {% block javascripts %}{% endblock %}
    </body>
</html>